[package]
name = "data_visualization"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_egui = "0.30"
rfd = "0.15.0"
bevy_obj = "0.14"
vtkio = "0.7.0-rc1"


[profile.dev]
opt-level = 0
debug = "full"

[profile.dev.package."*"]
opt-level = 0